services:
  - type: web
    name: ce-pune-website
    env: docker
    plan: free
    healthCheckPath: /
    healthCheckTimeout: 300
    startCommand: ./run.sh
    envVars:
      - key: PORT
        value: 10000
